name: android_ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  code_linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project sources
        uses: actions/checkout@v3

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: set up jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # Supported distributions: https://github.com/actions/setup-java#supported-distributions
          java-version: '17'

      - name: setup gradle
        uses: gradle/gradle-build-action@v2

      - name: create local.properties from secret variables
        run: echo API_KEY=${{ secrets.API_KEY }} > ./local.properties

      - name: create local.properties from secret variables
        run: echo HOST_KEY=${{ secrets.HOST_KEY }} > ./local.properties

      # KtLint
      - name: run ktlintCheck
        run: ./gradlew ktlintCheck

      - name: archive ktLint reports on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: code_linting
          path: "**/build/reports/ktlint/**/*.html"

      # Detekt
      - name: run detekt
        run: ./gradlew detekt
        if: success() || failure()

      - name: archive detekt reports on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: code_linting
          path: "**/build/reports/detekt/*.html"

  unit_tests:
    needs: code_linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout project sources
        uses: actions/checkout@v3

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: set up jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: setup gradle
        uses: gradle/gradle-build-action@v2

      - name: create local.properties from secret variables
        run: echo API_KEY=${{ secrets.API_KEY }} > ./local.properties

      - name: create local.properties from secret variables
        run: echo HOST_KEY=${{ secrets.HOST_KEY }} > ./local.properties

      # Run unit tests: https://developer.android.com/studio/test/command-line#run-tests-build-variants
      - name: run unit tests
        run: ./gradlew testDebugUnitTest

      - name: archive unit tests on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: unit_tests
          path: "**/build/reports/tests/testDebugUnitTest"